name: helium-pktfwd
base: core20
adopt-info: pktfwd
summary: Lora network packet forwarder
description: |
  The packet forwarder is a program running on the host of a Lora gateway
  that forwards RF packets receive by the concentrator to a server through
  a IP/UDP link, and emits RF packets that are sent by the server.
  It can also emit a network-wide GPS-synchronous beacon signal used for
  coordinating all nodes of the network.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
    run-on: arm64

apps:
  pktfwd:
    command: bin/start.sh
    daemon: simple
    restart-condition: always
    plugs:
      - gpio
      - network
      - network-control
      - network-bind
      - serial-port
      - spi

parts:
  pktfwd:
    source: https://github.com/Xykon/packet_forwarder.git
    plugin: make
    build-packages:
      - cmake
    build-environment:
      - LGW_PATH: "extern/lora_gateway/libloragw"
      - LoraGW_DIR: "extern/lora_gateway/libloragw"
    override-build: |
      pwd
      echo "Stage: $SNAPCRAFT_STAGE"
      cmake . -DWITH_VENDORED_HAL=ON
      make all
      # install
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -av lora_pkt_fwd/lora_pkt_fwd $SNAPCRAFT_PART_INSTALL/bin/
      cp -av lora_pkt_fwd/*.sh $SNAPCRAFT_PART_INSTALL/bin/
      # copy configs
      mkdir -p $SNAPCRAFT_PART_INSTALL/etc
      cp -av lora_pkt_fwd/cfg/* $SNAPCRAFT_PART_INSTALL/etc/
      #cp -av $SNAPCRAFT_STAGE/configs/*.json $SNAPCRAFT_PART_INSTALL/etc/
      # set version
      VER="$(cat VERSION)"
      echo "setting version to: $VER"
      snapcraftctl set-version "$VER"
  helper:
    source: .
    plugin: dump
    organize:
      start.sh: bin/start.sh
